title: Dang Bui Dinh's Homepage
page-top-title: Dang Bui Dinh
# top-section-bg-text: Computer Vision
home-subtitle: Dang Bui Dinh&ensp;
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
